### ISSUE TITLE
添加更多字到字体

### ISSUE THREAD

**Issue by eslym** [XoF-eLtTiL/LCTC#6]
steam好友里有些人用简体中文ID有些人用繁体中文ID，字体库里只有繁体字导致我这里时不时就会出现方框，看了难受

虽然我可以自己用unity打包字体但自己打包的不利于分享给朋友，另外打包成mod的话只会让thunderstore上平白再多一个xunity罢了

亲自测了一下cubic11和unifont和游戏的风格都挺贴合的，也不太缺字

字符列表则是这里拿的：https://github.com/rjtngit/rawchars

**Comment by CoolLKKPS** [comment]
雖然對我而言並不絕對需要，但這點我贊成！

**Comment by XoF-eLtTiL** [comment]
好吧

我之後會著手做簡體中文字庫
